apiVersion: v1
kind: Service
metadata:
  name: challenge
  labels:
    app.kubernetes.io/name: load-balancer-challenge
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: load-balancer-challenge
